package pageUIs.nopCommerce;

public class AdminCustomersUI {
	public static final String ADD_NEW_BUTTON = "//div[@class='pull-right']//a";
	public static final String EMAIL_TEXTBOX = "//input[@id='Email']";
	public static final String PASSWORD_TEXTBOX = "//input[@id='Password']";
	public static final String FIRSTNAME_TEXTBOX = "//input[@id='FirstName']";
 	public static final String LASTNAME_TEXTBOX = "//input[@id='LastName']";
	public static final String GENDER_MALE_RADIO_BUTTON = "//input[@id='Gender_Male']";
	public static final String DATE_OF_BIRTH_TEXTBOX = "//input[@id='DateOfBirth']";
	public static final String COMPANYNAME_TEXTBOX = "//input[@id='Company']";
	public static final String DELETE_BUTTON_ATCUSTOMER_ROLES = "//span[@aria-label='delete']";
	public static final String CUSTOMER_ROLES_DROPDOWN = "//label[@id='SelectedCustomerRoleIds_label']/parent::div/parent::div/following-sibling::div//div[@role='listbox']";
	public static final String GUEST_OPTION = "//li[text()='Guests']";
	public static final String GUEST_TEXT = "//ul[@id='SelectedCustomerRoleIds_taglist']//span[text()='Guests']";
	public static final String ADMIN_COMMENT_TEXTBOX = "//textarea[@id='AdminComment']";
	public static final String SAVE_AND_CONTINUE_EDIT_BUTTON = "//button[@name='save-continue']";
	public static final String SUCCESS_MESSAGE_TEXT = "//div[contains(@class,'alert alert-success alert-dismissable')]";
	public static final String BACK_TO_CUSTOMER_LIST = "//a[text()='back to customer list']";
	public static final String SEARCH_BUTTON = "//button[@id='search-customers']";
	public static final String INFOR_CUSTOMER_IN_TABLE = "//td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[@class=' text-center']//i[contains(@class,'%s-icon')]";
	public static final String EMAIL_TEXTBOX_IN_SEARCH_SECTION = "//input[@id='SearchEmail']";
	public static final String FIRSTNAME_TEXTBOX_IN_SEARCH_SECTION = "//input[@id='SearchFirstName']";
	public static final String LASTNAME_TEXTBOX_IN_SEARCH_SECTION = "//input[@id='SearchLastName']";
	public static final String COMPANYNAME_TEXTBOX_IN_SEARCH_SECTION = "//input[@id='SearchCompany']";
	public static final String MONTH_DROPDOWN_IN_SEARCH_SECTION = "//select[@id='SearchMonthOfBirth']";
	public static final String DAY_DROPDOWN_IN_SEARCH_SECTION = "//select[@id='SearchDayOfBirth']";
	public static final String DYNAMIC_EDIT_BUTTON_AT_CUSTOMERS = "//td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[@class=' text-center']//i[contains(@class,'%s-icon')]/parent::td/following-sibling::td/a[text()='Edit']";
	public static final String SAVE_BUTTON = "//button[@name='save']";
	
	public static final String ADD_NEW_ADDRESS_BUTTON = "//button[contains(text(), 'Add new address')]";
	public static final String ADDRESS_FIRSTNAME_TEXTBOX = "//input[@id='Address_FirstName']";
	public static final String ADDRESS_LASTNAME_TEXTBOX = "//input[@id='Address_LastName']";
	public static final String ADDRESS_EMAIL_TEXTBOX = "//input[@id='Address_Email']";
	public static final String ADDRESS_COMPANY_TEXTBOX = "//input[@id='Address_Company']";
	public static final String ADDRESS_COUNTRY_DROPDOWN = "//select[@id='Address_CountryId']";
	public static final String ADDRESS_STATE_DROPDOWN = "//select[@id='Address_StateProvinceId']";
	public static final String ADDRESS_CITY_TEXTBOX = "//input[@id='Address_City']";
	public static final String ADDRESS_ADDRESS1_TEXTBOX = "//input[@id='Address_Address1']";
	public static final String ADDRESS_ADDRESS2_TEXTBOX = "//input[@id='Address_Address2']";
	public static final String ADDRESS_ZIPCODE_TEXTBOX = "//input[@id='Address_ZipPostalCode']";
	public static final String ADDRESS_PHONE_NUMER_TEXTBOX = "//input[@id='Address_PhoneNumber']";
	public static final String ADDRESS_FAX_NUMBER_TEXTBOX = "//input[@id='Address_FaxNumber']";
	public static final String BACK_TO_CUSTOMER_DETAILS = "//a[text()='back to customer details']";
	public static final String INFOR_NEW_ADDRESS_IN_TABLE = "//td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td/div[text()='%s' and text()='%s' and text()='%s' and text()='%s,%s' and text()='%s']";
	public static final String INFOR_NEW_ADDRESS_HAS_STATEATIN_TABLE = "//td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td/div[text()='%s' and text()='%s' and text()='%s' and text()='%s,%s,%s' and text()='%s']";
	public static final String SAVE_BUTTON_AT_ADD_A_NEW_ADDRESS = "//button[contains(text(),'Save')]";
	public static final String DYNAMIC_EDIT_BUTTON_AT_CUSTOMER_DETAILS = "//td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td/div[text()='%s' and text()='%s' and text()='%s' and text()='%s,%s' and text()='%s']/parent::td/following-sibling::td//a[text()='Edit']";
	public static final String DYNAMIC_EDIT_BUTTON_HAS_STATEAT_CUSTOMER_DETAILS = "//td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td/div[text()='%s' and text()='%s' and text()='%s' and text()='%s,%s,%s' and text()='%s']/parent::td/following-sibling::td//a[text()='Edit']";
	public static final String DYNAMIC_DELETE_BUTTON_CUSTOMER_DETAILS = "//td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td/div[text()='%s' and text()='%s' and text()='%s' and text()='%s,%s' and text()='%s']/parent::td/following-sibling::td//a[text()='Delete']";
	public static final String DYNAMIC_DELETE_BUTTON_HAS_STATEAT_CUSTOMER_DETAILS = "//td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td[text()='%s']/following-sibling::td/div[text()='%s' and text()='%s' and text()='%s' and text()='%s,%s,%s' and text()='%s']/parent::td/following-sibling::td//a[text()='Delete']";
	public static final String NO_DATA_AVAILABLE_IN_TABLE = "//div[@id='customer-address']//td[@class='dataTables_empty']";
}
